### ISSUE TITLE
It is Production to use?

### ISSUE THREAD

**Issue by thearabbit** [VeprUA/react-multi-provider#11]
Thanks for your package.
Now I finding, how to solve multi context provider (Nested) config.
And could share each others

```js
<ProviderA>
  <ProviderB>
    <ProviderC>
             ................
    </ProviderC>
   </ProviderB>
</ProviderA>
```
Could use this for production mode?

**Comment by vepr-ua** [comment]
Yea you should be able to use the code for production!
