### ISSUE TITLE
Could not use `ContextProviderA` in `ContextProviderB`?

### ISSUE THREAD

**Issue by thearabbit** [VeprUA/react-multi-provider#12]
```   
 <MultiProvider providers={[
      <CounterProviderA />,
      <CounterProviderB />,
    ]}>
      {children}
    </MultiProvider>
```
Please help me

**Comment by vepr-ua** [comment]
Sorry for the late response.

Can you clarify your issue a bit more? Are you wondering if you can have a dependency of a `ProviderA` inside `ProviderB`? 
If so that is not currently supported, but if there is no workaround I'll be happy to see what I can do.
